replicaCount: 1

image:
  repository: ghcr.io/arboeckh/argocd-api:sha256-7bbf428df70fdd4d955e2c7b5ffec86e6e8c9c08d5b5192163872e9144d3de9a.sig
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: 30080

postgres:
  host: host.minikube.internal  # For Minikube, otherwise use localhost
  port: 5432
  dbname: dbprod
  user: newuser
  password: 12345


resources: {}
