replicaCount: 1

api:
  repository: ghcr.io/arboeckh/argocd-api@sha256:7c356cd740c831eb9989672ac29a9fd391f8b2576564c54a00d4273c39ed87d2
  pullPolicy: IfNotPresent

migration:
  repository: ghcr.io/arboeckh/argocd-schema:main
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: 30080

postgres:
  host: host.docker.internal  # For Minikube, otherwise use localhost
  port: 5432
  name: dbprod
  user: newuser
  password: 12345


resources: {}
