apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-api
  labels: 
    app: argocd-api
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Ensures it runs after the migration job
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: "{{ .Values.image.repository }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "{{ .Values.postgres.host }}"
        - name: DB_PORT
          value: "{{ .Values.postgres.port }}"
        - name: DB_NAME
          value: "{{ .Values.postgres.name }}"
        - name: DB_USER
          value: "{{ .Values.postgres.user }}"
        - name: DB_PASSWORD
          value: "{{ .Values.postgres.password }}"

