apiVersion: v1
kind: Service
metadata:
  name: argocd-api-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
